// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SeaMist")]
[assembly: AssemblyProductAttribute("SeaMist")]
[assembly: AssemblyDescriptionAttribute("A client SDK for Kraken.io.")]
[assembly: AssemblyVersionAttribute("0.1.1.6")]
[assembly: AssemblyFileVersionAttribute("0.1.1.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1.6";
        internal const string InformationalVersion = "0.1.1.6";
    }
}
