// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SeaMist")]
[assembly: AssemblyProductAttribute("SeaMist")]
[assembly: AssemblyDescriptionAttribute("SeaMist a .NET library for the Kraken.io REST API")]
[assembly: AssemblyVersionAttribute("0.1.1.7")]
[assembly: AssemblyFileVersionAttribute("0.1.1.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1.7";
        internal const string InformationalVersion = "0.1.1.7";
    }
}
